//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToursApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public long Id { get; set; }
        public int Number_Coupons { get; set; }
        public string Date { get; set; }
        public string Visit_purpose { get; set; }
        public double Price { get; set; }
        public long Id_Diagnosis { get; set; }
        public long Id_Doctor { get; set; }
        public long Id_Patient { get; set; }
    
        public virtual Diagnosis Diagnosis { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
